[package]
name = "rust_crypto"
version = "1.0.0"
edition = "2021"

[lib]
name = "rust_crypto"
crate-type = ["staticlib"]

[dependencies]
sha3 = "0.10.8"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
zeroize = { version = "1.7.0", features = ["derive"] }
hex = "0.4"

[build-dependencies]
cbindgen = "0.29.2"
